// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: proto/asyncTask.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WriteEsLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level           string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Timestamp       int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	File            string `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Msg             string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	ServerName      string `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Env             string `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`
	Uid             int64  `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	TraceId         string `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserAgent       string `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	HcAccessVersion string `protobuf:"bytes,10,opt,name=hc_access_version,json=hcAccessVersion,proto3" json:"hc_access_version,omitempty"`
	Url             string `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	RemoteAddr      string `protobuf:"bytes,12,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Data            string `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	Stack           string `protobuf:"bytes,14,opt,name=stack,proto3" json:"stack,omitempty"`
	Datetime        string `protobuf:"bytes,15,opt,name=datetime,proto3" json:"datetime,omitempty"`
}

func (x *WriteEsLogReq) Reset() {
	*x = WriteEsLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asyncTask_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEsLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEsLogReq) ProtoMessage() {}

func (x *WriteEsLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asyncTask_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEsLogReq.ProtoReflect.Descriptor instead.
func (*WriteEsLogReq) Descriptor() ([]byte, []int) {
	return file_proto_asyncTask_proto_rawDescGZIP(), []int{0}
}

func (x *WriteEsLogReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *WriteEsLogReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WriteEsLogReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *WriteEsLogReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *WriteEsLogReq) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *WriteEsLogReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *WriteEsLogReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WriteEsLogReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WriteEsLogReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *WriteEsLogReq) GetHcAccessVersion() string {
	if x != nil {
		return x.HcAccessVersion
	}
	return ""
}

func (x *WriteEsLogReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WriteEsLogReq) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *WriteEsLogReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *WriteEsLogReq) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *WriteEsLogReq) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

type WriteEsLogRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteEsLogRsp) Reset() {
	*x = WriteEsLogRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asyncTask_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEsLogRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEsLogRsp) ProtoMessage() {}

func (x *WriteEsLogRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asyncTask_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEsLogRsp.ProtoReflect.Descriptor instead.
func (*WriteEsLogRsp) Descriptor() ([]byte, []int) {
	return file_proto_asyncTask_proto_rawDescGZIP(), []int{1}
}

var File_proto_asyncTask_proto protoreflect.FileDescriptor

var file_proto_asyncTask_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d,
	0x03, 0x0a, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x63, 0x5f,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x68, 0x63, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x0f,
	0x0a, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x73, 0x70, 0x32,
	0x45, 0x0a, 0x09, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x38, 0x0a, 0x0a,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x73,
	0x4c, 0x6f, 0x67, 0x52, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_asyncTask_proto_rawDescOnce sync.Once
	file_proto_asyncTask_proto_rawDescData = file_proto_asyncTask_proto_rawDesc
)

func file_proto_asyncTask_proto_rawDescGZIP() []byte {
	file_proto_asyncTask_proto_rawDescOnce.Do(func() {
		file_proto_asyncTask_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_asyncTask_proto_rawDescData)
	})
	return file_proto_asyncTask_proto_rawDescData
}

var file_proto_asyncTask_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_asyncTask_proto_goTypes = []interface{}{
	(*WriteEsLogReq)(nil), // 0: Proto.writeEsLogReq
	(*WriteEsLogRsp)(nil), // 1: Proto.writeEsLogRsp
}
var file_proto_asyncTask_proto_depIdxs = []int32{
	0, // 0: Proto.AsyncTask.writeEsLog:input_type -> Proto.writeEsLogReq
	1, // 1: Proto.AsyncTask.writeEsLog:output_type -> Proto.writeEsLogRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_asyncTask_proto_init() }
func file_proto_asyncTask_proto_init() {
	if File_proto_asyncTask_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_asyncTask_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEsLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_asyncTask_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEsLogRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_asyncTask_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asyncTask_proto_goTypes,
		DependencyIndexes: file_proto_asyncTask_proto_depIdxs,
		MessageInfos:      file_proto_asyncTask_proto_msgTypes,
	}.Build()
	File_proto_asyncTask_proto = out.File
	file_proto_asyncTask_proto_rawDesc = nil
	file_proto_asyncTask_proto_goTypes = nil
	file_proto_asyncTask_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AsyncTaskClient is the client API for AsyncTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AsyncTaskClient interface {
	WriteEsLog(ctx context.Context, in *WriteEsLogReq, opts ...grpc.CallOption) (*WriteEsLogRsp, error)
}

type asyncTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncTaskClient(cc grpc.ClientConnInterface) AsyncTaskClient {
	return &asyncTaskClient{cc}
}

func (c *asyncTaskClient) WriteEsLog(ctx context.Context, in *WriteEsLogReq, opts ...grpc.CallOption) (*WriteEsLogRsp, error) {
	out := new(WriteEsLogRsp)
	err := c.cc.Invoke(ctx, "/Proto.AsyncTask/writeEsLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncTaskServer is the server API for AsyncTask service.
type AsyncTaskServer interface {
	WriteEsLog(context.Context, *WriteEsLogReq) (*WriteEsLogRsp, error)
}

// UnimplementedAsyncTaskServer can be embedded to have forward compatible implementations.
type UnimplementedAsyncTaskServer struct {
}

func (*UnimplementedAsyncTaskServer) WriteEsLog(context.Context, *WriteEsLogReq) (*WriteEsLogRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteEsLog not implemented")
}

func RegisterAsyncTaskServer(s *grpc.Server, srv AsyncTaskServer) {
	s.RegisterService(&_AsyncTask_serviceDesc, srv)
}

func _AsyncTask_WriteEsLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteEsLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncTaskServer).WriteEsLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proto.AsyncTask/WriteEsLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncTaskServer).WriteEsLog(ctx, req.(*WriteEsLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AsyncTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Proto.AsyncTask",
	HandlerType: (*AsyncTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "writeEsLog",
			Handler:    _AsyncTask_WriteEsLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asyncTask.proto",
}
